{{- if .Values.policies.defaultDenyEgress }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "shieldai.fullname" . }}-default-deny-egress
  namespace: {{ include "shieldai.namespace" . }}
  labels:
    {{- include "shieldai.labels" . | nindent 4 }}
    shieldai.io/policy: default-deny-egress
spec:
  podSelector:
    matchLabels: {{ .Values.podSelector | default dict | mustToJson }}
  policyTypes:
    - Egress
{{- end }}
